// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1DKpo8vaRcGHnH5rUcKRAZSdtQiK9XPc',
    appId: '1:222450165342:web:6b10a84958d1bc8a26b6cf',
    messagingSenderId: '222450165342',
    projectId: 'denemeproje-5ef72',
    authDomain: 'denemeproje-5ef72.firebaseapp.com',
    storageBucket: 'denemeproje-5ef72.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqe0-4BSzmoKLrJBGX5N2_B1itQ9w-RrE',
    appId: '1:222450165342:android:f7ec7774b559fea526b6cf',
    messagingSenderId: '222450165342',
    projectId: 'denemeproje-5ef72',
    storageBucket: 'denemeproje-5ef72.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoAKasRNtLCRduuBPPVAxAFKUwdA0CKOM',
    appId: '1:222450165342:ios:873e776f05f0e85a26b6cf',
    messagingSenderId: '222450165342',
    projectId: 'denemeproje-5ef72',
    storageBucket: 'denemeproje-5ef72.firebasestorage.app',
    iosBundleId: 'com.example.whatsup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoAKasRNtLCRduuBPPVAxAFKUwdA0CKOM',
    appId: '1:222450165342:ios:873e776f05f0e85a26b6cf',
    messagingSenderId: '222450165342',
    projectId: 'denemeproje-5ef72',
    storageBucket: 'denemeproje-5ef72.firebasestorage.app',
    iosBundleId: 'com.example.whatsup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1DKpo8vaRcGHnH5rUcKRAZSdtQiK9XPc',
    appId: '1:222450165342:web:7612ce9063997b1c26b6cf',
    messagingSenderId: '222450165342',
    projectId: 'denemeproje-5ef72',
    authDomain: 'denemeproje-5ef72.firebaseapp.com',
    storageBucket: 'denemeproje-5ef72.firebasestorage.app',
  );

}